# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[git]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    { message = "^feat", group = "ğŸš€ Features" },
    { message = "^fix", group = "ğŸ› Bug Fixes" },
    { message = "^refactor", group = "ğŸšœ Refactor" },
    { message = "^doc", group = "ğŸ“š Documentation" },
    { message = "^perf", group = "âš¡ Performance" },
    { message = "^style", group = "ğŸ¨ Styling" },
    { message = "^test", group = "ğŸ§ª Testing" },
    { message = "^chore", group = "âš™ï¸ Chore", skip = true },
    { body = ".*security", group = "ğŸ›¡ï¸ Security" },
    { message = "^revert", group = "â—€ï¸ Revert" },
    { message = ".*", group = "ğŸ’¼ Other", skip = true },
]
